- legislators-current.yaml
Looks like something was amiss in the new_leg spreadsheet (Coble's bioguide id had been in the new_id column), so we added an extra term for Rep. Coble, who retired. He's replaced by [Bradley Walker](http://bioguide.congress.gov/scripts/biodisplay.pl?index=W000819) in the NC-6.
> Add Bradley Walker and move Rep. Coble to legislators-historical.yaml

- legislators-current.yaml
For Senate leadership I have the last role ending '2015-01-03' and starting '2015-01-03' 
For House leadership, since they had a vote for roles on the 6th, their old roles end on '2015-01-03' and new ones start on '2015-01-06'
(I also caught a typo)
> Updated `leadership_roles' fields for the 114th

- legislators-social-media.yaml
This isn't all of them. Also note that these commits do not resolve situations like that of Senator Lankford, who switched chambers and no longer is available at @RepLankford.
Happy to clean up a bit before merge (see, e.g., the anomalous accounts not included in commits), but wanted to get a conversation going.
* Newhouse
* Jenkins
* Ratcliffe
* Loudermilk (* house website embeds @housegop twitter account)
* Carter
* Curbelo
* MacArthur
* Bost
* Comstock
* Ashford
* Poliquin
* Moolenaar
* Stefanik
* Costello
* Rouzer
* Palmer
* McSally
* Emmer
* Russell
* Abraham
* Young
* Zeldin
* Graham
* Katko
* Zinke
* Hill (not linked from House site, but @RepFrenchHill links back to hill.house.gov)
* Babin
* Mooney
* Trott
* Buck
* Blum
* Bishop
* Rice
* Dingell
* Alma Adams
* Westerman
* Frank …
> Twitter Accounts for Some New Members

- legislators-current.yaml
Does this repo grab data from the contact-congress repo for contact links? That repo is perhaps the most up to date for contact form links.
> Update contact_form link

- legislators-social-media.yaml
Updates for social media accounts of Sen. Cory Gardner via http://www.gardner.senate.gov/
Note, I don't see a valid 'youtube' just a 'youtube_id' linked from his official page. Youtube channel/user/names are weird.
> Update social media accounts for Sen. Cory Gardner

- committee-membership-current.yaml
- committees-current.yaml
This is the output of `committee_membership.py`, run with `scrape_house_alt()` instead of the deprecated `scrape_house()`. I spot checked quite a few of the committee and subcommittee member lists, and they looked pretty good, with the following exceptions:
* House Committee on Natural Resources (`HSII`) subcommittees only have ex officio members.
* Senate Committee on Environment and Public Works (`SSEV`) subcommittees still have no members.
* **Some committees may have outdated House members**, since the House [doesn't publish joint committee members](https://github.com/unitedstates/congress-legislators/blob/master/scripts/committee_membership.py#L285). I manually cleaned up Commission on Security and Cooperation in Europe (`JCSE`) ([data …
> Most Committees for 114th Congress

- legislators-social-media.yaml
Discovered this was missing the verified Twitter account [@RepSamGraves](https://twitter.com/RepSamGraves/) that links to his House.gov site, but his site [doesn't link back to this Twitter account](http://graves.house.gov/). Called his office and the communications director confirmed that it is his official House Twitter account.
> Adding Rep. Sam Graves

- README.md
- legislators-social-media.yaml
- scripts/data/social_media_blacklist.csv
- scripts/social_media.py
- scripts/utils.py
So it looks like about a quarter of members link to their Instagram account on their official page. I made this PR to track work on the `instagram` branch and provide a place for discussion/review.
All of the Instagram accounts added in `legislators-social-media.yaml` come from a scrape of members' official websites (see update to `social_media.py`). Assuming that we're willing to regard an Instagram linked from an elected official's page as — well — official, these just need a once over to make sure the scraper's Instagram regex didn't grab a false account. If presence on a member's official homepage != official Instagram account status, we should hammer out details for what constitutes an "official" Instagram account and then figure out how to verify these. Unfortunately, I don't see …
> Instagram handles [needs discussion]

- legislators-current.yaml
Added Rick Allen's correct FEC ID H2GA12121 and removed FEC ID H0GA02241. 
Pretty sure about this, but would love it if someone could confirm: H0GA02241 is a different Rick Allen who lost in the Republican primary for GA-02 in 2012. H2GA12121 is the correct FEC ID for the Rick Allen elected to GA-12 in 2014.
http://ballotpedia.org/Rick_Allen vs.
http://ballotpedia.org/Rick_Allen_(Georgia_2nd)
> Corrected Rick Allen's FEC ID

- legislators-social-media.yaml
Added all social media accounts of Rep. Hardy following an email request from his communications director, Scott Knuteson. The official Twitter and Facebook accounts are linked here: https://hardy.house.gov/
While the Youtube account is not linked from the homepage, it was specifically mentioned by Knuteson in the email and can be seen used on this page: https://hardy.house.gov/media-center/videos/womens-history-month-remarks-recognizing-betty-wall
> Adding Rep. Cresent Hardy

- legislators-social-media.yaml
[@RepJustinAmash](https://twitter.com/repjustinamash) is now a private account and there's no Twitter accounts linked from [Amash.house.gov](http://amash.house.gov/)
> Rep. Justin Amash no longer has an official Twitter account

- legislators-social-media.yaml
It appears as if Sen. Cantwell's Twitter screen name has changed and unsavory elements have taken over her old one.
> Update Sen. Cantwell's Twitter account

- legislators-current.yaml
- scripts/house_websites.py
House MoC URLs used to occasionally be subpaths, in earlier times, but today they're always subdomains. We can safely omit everything after the `.gov`.
We still don't naively trust the official directory, and follow redirects from whatever domain is given. This has the effect of occasionally fixing out-of-date domains (e.g. the directory lists `randyforbes.house.gov` which redirects to `forbes.house.gov`). 
This also removes some `www` subdomains and moves some URLs to `https://` (though these could also be a function of just not having run this script in a while).
Fixes #300. Thanks to @gmj2053 for reporting this and motivating the fix!
> Don't include trailing paths in official members' website URLs

- .travis.yml
This [moves us away from Travis' legacy infrastructure](http://docs.travis-ci.com/user/migrating-from-legacy/), for faster Docker-based builds. Doing a PR to make sure it works before merging.
> Move to new Travis infrastructure

- legislators-social-media.yaml
- scripts/social_media.py
Adds Dana Rohrabacher's YouTube account, as pointed out in #308. 
This also updates the YouTube sweeper to look for YT embed widgets, even though the captured slug is not expected to be the real ID. It will drop it in the spreadsheet as a pretty obviously invalid result (starting with `list=`) and the reviewer is expected to go find the real username and replace it.
During this, I _think_ I also discovered that the YT ID resolver looks to no longer be working. I could use some verification of this.
> Add Dana Rohrabacher's YouTube account

- legislators-current.yaml
This corrects term end dates in historical terms. Per #7, we wanted to fix term end dates to be the Constitutionally-defined end of a term.
In summary, this commit does a simple string substitution to correct the following dates:
2nd Congress 1793-03-02 => 1793-03-03
22nd Congress 1833-03-02 => 1833-03-03
73rd Congress 1934-06-18 => 1935-01-03
74th Congress 1936-06-20 => 1937-01-03
75th Congress 1938-06-16 => 1939-01-03
77th Congress 1942-12-16 => 1943-01-03
78th Congress 1944-12-19 => 1945-01-03
79th Congress 1946-08-02 => 1947-01-03
80th Congress 1948-12-31 => 1949-01-03
81st Congress 1951-01-02 => 1951-01-03
82nd Congress 1952-07-07 => 1953-01-03
83rd Congress 1954-12-02 => 1955-01-03
84th Congress 1956-07-27 => 1957-01-03
85th Congress 1958-08-24 => 1959-01-03
86th Congress 1960-09-01 …
> Correct term end dates in historical terms, per #7

- legislators-current.yaml
Added OpenSecrets IDs for Daniel Donovan (N00036928) and TrentKelly
(N00037003).
Not meaning to step on anyone's toes -- I don't know how these IDs are
normally added. I got them from the urls of these pages:
http://www.opensecrets.org/politicians/summary.php?cid=N00036928&cycle=2016
http://www.opensecrets.org/politicians/summary.php?cid=N00037003&cycle=2016
after searching by name here:
http://www.opensecrets.org/politicians/summary_all.php
Cool?
> added 2 OpenSecrets IDs

- .travis.yml
It seems osx builds on travis-ci don't natively support python.  They made a change 26 days ago where these builds started failing instead of being ignored.
> Until today, the os: osx with language: python was discarded, and only Linux builds were created.
refs:
https://github.com/travis-ci/travis-ci/issues/4729
https://github.com/travis-ci/travis-ci/issues/2312
> remove failing osx build in travis-ci

- legislators-current.yaml
Adding missing links to Wikipedia for those entries missing Wikipedia
links.
Also, on a trial basis, including links to Wikidata as well. Wikidata
IDs are stable identifiers, meaning they will continue referring to the
member of Congress in question even if the article is renamed. The
compromise reached by myself and Konklone is to list both side by side
for the time being, with the Wikidata ID being used to occasionally
check to see that the Wikipedia page titles are up to date. I will add
Wikidata IDs for the rest of them as soon as I find an efficient way to
do so.
> Adding missing Wikipedia links; adding some Wikidata links

- legislators-current.yaml
Got Wikidata IDs for the rest of them by starting with the Wikipedia
titles, auditing them to make sure they were referring to the right
person, and then adding the ID in. I updated page titles for articles
that were renamed; in the future, a script will be able to do this
automatically based on the Wikidata ID. The question is to how to do
this automatically in the long term.
> Wikidata IDs and updated Wikipedia article titles for all

- legislators-social-media.yaml
Placed a space after Speaker Ryan's twitter account name, forming valid yaml.
> Valid yaml for Speaker Ryan's twitter

- scripts/house_history.py
This was meant to be in PR #340 but I forgot to push the commit, so here it is!
If you wanted to catch these sooner, how about moving pyflakes from `after_success:` to the end of `script:` in .travis.yml?
> Remove unused import

- .travis.yml
Helps avoid things like https://github.com/unitedstates/congress-legislators/pull/341 by failing PRs on Travis CI if there are pyflakes problems.
It does this after the main tests, so it you'll always get the results of those first.
> catch pyflakes sooner

- legislators-current.yaml
- scripts/house_contacts.py
From #276, the Clerk of the House provides XML for member information.  There are several name fields in the XML that the Clerk provides that do not directly match the name fields in legislators-current.
> Move to import house contacts from the Clerk XML feed

- README.md
Add EveryPolitician.org to the "Who's Using This Data" section.
> Add EveryPolitician to README

- legislators-social-media.yaml
Is [SenMarkey](https://twitter.com/SenMarkey). Was [MarkeyMemo](https://twitter.com/MarkeyMemo). Appears on http://www.markey.senate.gov/.
> Sen. Ed Markey has a new Twitter handle: SenMarkey

- legislators-current.yaml
- scripts/committee_membership.py
- scripts/house_websites.py
- scripts/senate_contacts.py
I ran `house_contacts.py` and `senate_websites.py`, and updated them (and the `committee_membership.py` script) to use `https://` URLs for `house.gov` and `senate.gov`.
> Update House websites, a Senate website, and some data source URLs

- legislators-current.yaml
Birthdate for Jason Lewis was incorrect, correct birthdate can be seen here: http://bioguide.congress.gov/scripts/biodisplay.pl?index=L000587
> Fix birthdate for Jason Lewis from MN district 2

- legislators-social-media.yaml
- scripts/data/social_media_blacklist.csv
This does a full sweep of Twitter and Facebook accounts. This scans MoC house.gov and senate.gov pages (for any MoC where we don't have an account for them already) and looks for links to twitter.com and facebook.com links, subject to filtering out common false positives.
I went and hand-verified that every Twitter account either links back to the house.gov/senate.gov site (or was otherwise clearly not a campaign account and positively linked to from the house.gov/senate.gov site), and hand-verified that every discovered Facebook account either has a verified checkmark for a Page set to Government Official, or that it links back to the homepage or is otherwise clearly not a campaign account. I also sanity checked every Twitter and Facebook handle to make sure it matched up with the name …
> Updated Twitter and Facebook social media accounts

- congress_lookup.py
- legislators-current.yaml
Add the ability to look up specific fields by committee membership or member last name. Wildcards are used. For example,
```
python congress_lookup.py -c 'Financ*' phone fax
```
prints the phone and fax numbers of all members of the **Senate Committee on Finance** and the **House Committee on Financial Services**.
The command
```
python congress_lookup.py -n Smith fax hours
```
prints all fax numbers and hours listed for any legislator named "Smith".
There are also updates to the current legislator database per #411.
This is a commit-specific resubmission of #405.
> Lookup legislator properties by name and committee membership, update fax numbers

- legislators-current.yaml
Gramm's resignation was effective 11/30/2002, and Cornyn served in the interim - 11/30/2002 to the end of the session, 01/03/2003
> Fixed the terms for TX Sens Gramm and Cornyn

- legislators-social-media.yaml
Adds twitter handles for Amash, Hanabusa, Rand Paul, and Rohrabacker, and run social_media.py --resolvetw.  resolvetw showed we had some incorrect twitter ids.
Amash's twitter wasn't linked from his website but the twitter account links to his facebook which links to his official website, which seemed official enough.
> add twitter handles for 2 legislators and run resolvetw to fix some twitter ids

- scripts/social_media.py
I noticed when running social_media.py --verify [--resolvetw], candidate_for is currently returning the first regex that passes.  This changes the logic to return the existing candidate first if its found.  This causes the output of the script to be less verbose, like so:
[W000437] mismatch on http://www.wicker.senate.gov - SenatorWicker -> AjitPaiFCC
Also, would anyone object to making lines like this debug-only?
Found redirect, downloading http://www.thune.senate.gov/public/ instead..
> prefer existing social media over first found

- legislators-current.yaml
2 more address changes for Senators, originally left out because they didn't match the senators websites but confirmed with senate.gov people that the websites just haven't been updated yet following a recent room change.
> senator address updates

- legislators-current.yaml
- scripts/house_websites.py
I did a sweep of House site URLs, and fixed the House website scraper to properly handle Delegates and Resident Commissioners. Mostly it's updating House URLs from http -> https, but there's at least one actual URL change in there.
> Sweep of House website updates, fixed scraper

- legislators-social-media.yaml
Adds social data for `N000190` in alignment with [official site](https://norman.house.gov/)
> Add social for N000190

- legislators-social-media.yaml
The account isn't linked from his homepage anymore and doesn't exist on twitter. I think the numeric ID is invalid now so that means the account was deleted/inactivated and not renamed.
> SenKaineOffice (twitter) seems to have been deleted

- committee-membership-current.yaml
- scripts/committee_membership.py
For some reason, running committee_membership.py now suddenly reverses the thomas and bioguide ID fields compared to the order that we have in the YAML file, creating spurious diffs.
We were using a dict to pass this information, and dicts have been unordered (though that changes in CPython 3.6, though I'm running 3.5 so that wasn't the problem), so the order was only lucky to be stable until now. It's surprising we got this far without seeing them flip.
Changing it to an OrderedDict should guarantee the order that we want.
This PR also updates the committee-membership-current.yaml data file after running the script.
See #546.
> committee membership ID order

- legislators-current.yaml
Recently-ish we added the `caucus` field to indicate the party Independents caucus with. We currently have it set for Sen. Sanders's current term, Sen. King (who is in his first term), and MP's delegate Rep. Sablan's previous term (he's currently a Democrat but was an Independent).
This PR sets it for all of Sanders's previous terms so that his party+caucus affiliation is consistent for all of his terms, and it makes it so all terms in legislators-current with `party: Independent` have `caucus:` set.
> mark Sen. Sanders as having always caucused with the Democrats

- legislators-current.yaml
- scripts/house_contacts.py
For consistency with the `office` field and Senate contact info which uses Senate Office Building throughout.
Fixes #550.
> expand out "HOB" to "House Office Building" in address field

- legislators-district-offices.yaml
Add all four district offices for Tina Smith (Moorhead, Duluth, Rochester, St. Paul).
The lack of these entries was causing `test/validate.py` to fail.
> Add district offices for Sen. Tina Smith (MN)

- scripts/office_validator.py
Fixes #576, but still warns for offices with address but missing latitude and longitude.
> Don't error on missing latitude/longitude

- legislators-district-offices.yaml
Dave Joyce (OH-14) moved his office from Painesville, Ohio to Mentor, Ohio. 
Old address: 
1 Victoria Pl. Room 320 
Painesville, OH 44077
New address: 
8500 Station St, Suite 390 
Mentor, OH. 44060 
URL proof: https://joyce.house.gov/my-office-locations/ 
h/t @shannonturner for the tip.
> Updated office address for Dave Joyce (OH-14)

- legislators-social-media.yaml
Fixing capitalization for Don Beyer's social media Twitter and Facebook accounts (repdonbeyer -> RepDonBeyer) and adding Rand Paul's twitter handle (@RandPaul)
> Fixing capitalization and adding twitter account

- legislators-social-media.yaml
Both #579 and #591 added Rand Paul's Twitter account, but they were added in different places, so Git did not automatically remove the duplicate addition. Remove it so the lints can pass.
> Remove duplicate Twitter account for Rand Paul

- committees-current.yaml
Some RSS links are broken and do not appear to have replacements.
Energy/Commerce's jurisdiction source is also broken, but their new jurisdiction page is less thorough, so I left it alone.
> Use https for House Committee urls. Fix (some) RSS links.

- legislators-current.yaml
I've started a branch (and this PR) for special election results.
According to https://ballotpedia.org/Special_elections_to_the_115th_United_States_Congress_(2017-2018) and other sources there were six special elections plus one election (OK-1) that included simultaneously filling a vacancy:
| Contest | Result |
| --------- | -------- |
| MN (senate) | Smith |
| MS (senate) | runoff |
| MI-13 | Jones |
| NY-25 | Morelle |
| OK-1 | Hern |
| PA-7 | no data on CNN |
| PA-15 | no data on CNN |
Sen. Smith (MN) won reelection and so the one commit in this PR adds a term for her. I set the end/start dates to Nov 6/7 for now. I imagine she will be sworn in again later this month, and in that case we should update the turnover dates to that date, I think, and then merge the change, maybe?
The …
> Nov 2018 Special Election Results - Smith, Morelle, Hern

- .circleci/config.yml
Oftentimes, the lint will fail for some reason or another, but we should still deploy the latest changes to GitHub pages. Remove the requirement that the build step must succeed for deploy to occur.
> Don't require build success for deploy

- legislators-current.yaml
Two new Senators accidentally had their old House URLs put in for their Senate term. Fix these two URLs to point to their new Senate URLs.
> Fix two Senate URLs

- legislators-current.yaml
Pretty much like you'd expect: added `wikipedia` IDs for all the incoming congresspeople I could find on Wikipedia.
Example:
```yaml
- id:
bioguide: D000630
fec:
- H8NY19181
govtrack: 412805
wikipedia: Antonio Delgado (politician)
name:
first: Antonio
last: Delgado
```
> 116th legislator wikipedia ids

- legislators-social-media.yaml
Not sure if RepIlhanOmar was never the right name or if it was made private or deleted.
> SenBennetCo twitter account was renamed, RepIlhanOmar disappeared

- legislators-current.yaml
#492
For consistency with official full name, and other public sources.
> Remove accent from Robert Menendez's last name.

- executive.yaml
- legislators-current.yaml
- test/validate.py
This data came from my original import from GovTrack's legislator database, and the religion field probably came from my original import of data from the MIT Media Lab's Government Information Awareness project in 2003. The field was never maintained. To avoid confusion over an unmaintained field, per #657 and 9101feaae3ec45418d9e0806df656df7b74ff22e, this PR removes it.
> remove the old religion data

- committee-membership-current.yaml
- committees-current.yaml
- legislators-current.yaml
This PR updates House and Senate committee and subcommittee assignments for the 116th Congress. There are some important notes:
1. It adds a `start_date` and `source` attribute to assignments, tied to House/Senate resolutions announcing membership or committee press releases announcing subcommittee assignments. Both are optional.
2. There are a handful of committees and subcommittees without current assignments. These include all of the joint committees and some of the select committees (including House select committees on climate change and modernization of Congress). The new select committees also are not yet in the `committees_current.yaml` file.
3. There is one subcommittee, Elections of House Administration, that is new and does not yet have either a clerk code or what we call a …
> 116th Congress Committee Assignments

- legislators-current.yaml
I found these ids while searching through
https://www.fec.gov/data/candidates/
For Joe Neguse and David Trone I couldn't actually find the FEC ids that
we currently have here on https://www.fec.gov/data/candidates/,
but I didn't remove them because I am assuming
they are coming from some other data source and it may make sense to do
some digging upstream to see why there is a mismatch.
For Mitt Romney we had the FEC id for Massachusetts,
but he is in Utah now.
Fixes https://github.com/unitedstates/congress-legislators/issues/665
> Add missing FEC ids

- committee-membership-current.yaml
https://homeland.house.gov/about/committee-membership show Mike Rogers
as the ranking member for the House Committee on Homeland Security
(HSHM) and https://judiciary.house.gov/about/members shows Doug Collins
as the ranking member for House Committee on the Judiciary (HSJU).
> Add missing titles for Ranking Members

- legislators-current.yaml
This PR includes updated contact information for both House and Senate members as produced by the scripts `scripts/senate_contacts.py` and `scripts/house_contacts.py` respectively.
I had originally run the senate script because I noticed that Joni Ernst's office was outdated, and then I found that there were a handful of Senate offices that had changed, in addition to URLs and emails.
The House updates only include changes to members' full names.
I hand-audited roughly 50% of the office/URL changes to validate.
> Update contact info

- committee-membership-current.yaml
- committees-current.yaml
The subcommittee's name was changed and the press release with assignments appears to have been mistranscribed.
This was reported to GovTrack by a user.
> corrections for Senate Commerce subcommittee on Aviation and Space

- legislators-district-offices.yaml
Updated district office information for all current members of Congress, normalized and geocoded.
I spot checked other warnings from validation about missing fields and filled in data where appropriate.
The following members of Congress do not have any district office information listed:
M001208 [GA rep] Lucy McBath (https://mcbath.house.gov/)
T000484 [NM rep] Xochitl Torres Small (http://torressmall.house.gov)
A000376 [TX rep] Colin Z. Allred (https://allred.house.gov/)
H001089 [MO sen] Josh Hawley (https://www.senate.gov/senators/116thCongress/HawleyJosh.htm)
W000827 [TX rep] Ron Wright (https://wright.house.gov/)
This is a large set of changes, so it's probably not practical to verify every line, but a few spot-checks would be appreciated!
> Update district offices for 116th Congress

- committee-membership-current.yaml
- committees-current.yaml
- legislators-district-offices.yaml
- scripts/committee_membership.py
Although @dwillis did a lot of work on manually collecting committee membership, there is a lot of new data and some errors. We have a scraper, but now that the data has membership start dates and links to sources, the scraper needed to be updated to preserve existing data in the file.
I updated the scraper. The result was a lot of changes. So I ran it in stages (full committees first, then (missing) subcommittees we didn't have, then subcommittees we already had) so we have at least one commit with a readable diff.
I also added the House Select Committee on the Climate Crisis and the House Select Committee on the Modernization of Congress to the metadata since they are on the Clerk site and have members.
> Scrape committee membership

- legislators-current.yaml
This is the birthday now reported on http://bioguide.congress.gov/scripts/biodisplay.pl?index=S001215. It was probably wrong on bioguide earlier, or maybe didn't have the day of the month. See 7ac8df9ce1392eb04cc7c53637333bd3e0e7cf81.
> update Rep. Stevens's birthday

- legislators-current.yaml
I noticed that 19 of the current legislators were missing Open Secrets IDs, so I added them from the list of IDs available from Open Secrets [here](https://www.opensecrets.org/open-data/api-documentation). Please let me know if there's anything else I need to do, I'd be happy to help.
> Add missing Open Secrets Candidate IDs

- legislators-current.yaml
Four current senators were missing Senate FEC ID's. Each of these had (correct but outdated) House of Represenatives FEC ID's, which may help explain why it went unnoticed by the scripts.
> Add missing Senate FEC ID's

- committees-current.yaml
build fails on circleci due to lint error, due to comments being disallowed by linter configuration.
preserve information in comment fields.
> committees-current.yaml: move comments to comment fields

- legislators-current.yaml
fixes circle-ci:
> legislators-current.yaml:K000395:terms[0](2019-06-03 to 2021-01-03) Term is missing a website url.
> legislators-current.yaml: add url

- legislators-current.yaml
- scripts/house_websites.py
The house_websites.py script was not finding any URLs due to a change in the HTML of the House directory page.
This change fixes the script, and updates current House member URLs based on the fixed script.
Most changes are just to remove a trailing slash or do http->https, but there are a few substantive changes as well.
> Update house websites script

- legislators-current.yaml
- misc/new-member-template.yaml
Neither one is on Bioguide yet. I guessed Murphy's bioguide ID from the next available M number; GPO bill XML is already giving the id for Biship. Bishop's birthday is from Wikipedia; Murphy's birthday is omitted --- I can't find a source.
address/office/phone is from running house_contacts.py.
> add Rep. Murphy, Rep. Bishop

- legislators-current.yaml
- scripts/icpsr_ids.py
Fixes #601
Current urls for getting Vote View data are being depreciated. This PR updates the urls in icpsr_ids.py script to adhere to new format. Script also had to be updated to handle the new data being returned by Vote View. Ran the script and updated icpsr ids for legislators-current.yaml. Now, the icpsr_ids.py script correctly queries Vote View and sets the icpsr id for current and historical legislators (based off congress number passed to script).
> icpsr ids - fix issue #601

- legislators-district-offices.yaml
Looked up and added offices for Gregory F. Murphy and Dan Bishop.
Fixes error due to missing them, and being in office more than 60 days
Signed-off-by: Tom Scanlan <tompscanlan@gmail.com>
Fixes these errors:
``` bash
$  python3 test/validate.py
legislators-current.yaml:A000367:terms[4](2019-01-03 to 2021-01-03) caucus: ~
when party is Independent.
Vacancy in CA district 25 .
Vacancy in MD district 7 .
Vacancy in NY district 27 .
Vacancy in WI district 7 .
M001210 [NC rep] Gregory F. Murphy (https://gregmurphy.house.gov/)
ERROR: No offices
B001311 [NC rep] Dan Bishop (https://danbishop.house.gov/)
ERROR: No offices
```
Now should be:
``` bash
$ python3 test/validate.py
legislators-current.yaml:A000367:terms[4](2019-01-03 to 2021-01-03) caucus: ~
when party is Independent.
Vacancy in CA …
```
> Add district offices for NC

- legislators-social-media.yaml
This PR adds missing Twitter IDs only for legislators who already have
a Twitter handle present in the data. I don't know if these are campaign
accounts or not; these are just the IDs for accounts that are already
there.
> Add missing IDs for Twitter handles

- test/validate.py
I was looking at whether Rep. Mfume's 24-year absence from Congress was a record (no, Maryland congressman [Rep. Phillip Thomas](https://www.govtrack.us/congress/members/phillip_thomas/410763) seems to hold that record, with a 34-year absence between 1841-1875).
In the process I found some data errors that all appear to be duplicates of the entire terms of representatives hidden in similar-named representatives. These edits seem to date back to my original 2009 parse of Bioguide. This PR removes those duplicates and makes some fixes that I found while researching the errors.
> Historical fixes

- .circleci/config.yml
There was a probably-transient error in #723. This probably has nothing to do with that, but is probably a good idea anyway.
> Update CircleCI docker image to Python 3.8, drop -browsers

- legislators-district-offices.yaml
Biddeford office replaces Scarborough per website: https://www.king.senate.gov/contact/office-locations
> Update office for Angus King

- committee-membership-current.yaml
This is based off [this Clerk document](https://clerk.house.gov/committee_info/scsoal.pdf) plus several subsequent House resolutions naming members. It does not include Marjorie Taylor Greene, who was removed from two committees, or Ron Wright, who died in early February. It also is currently missing the House select committees (Intel, Climate and Modernization) and House assignments to joint committees.
If folks want to wait until we get those to merge, that's ok with me.
> Added House standing full committee assignments

- legislators-current.yaml
He uses Jim on official documents, but the logic I am trying to follow nowadays is if the person's legal first name is recognizable as them, then the legal first name stays in the first name field.
> Add 'Jim' nickname to Rep. James Himes

- .circleci/config.yml
it looks like the branch filter was left as master despite the name changing to main
> fix circleci config to run deploy step again

- README.md
- committees-current.yaml
I found these useful for a project and thought it would save others time if they were incorporated into the base repo.
Although legislators' social media accounts are in a separate yaml file, I suggest putting the committees' YouTube channel ID directly on the current committees list both for convenience and since it does not need to be updated with the same frequency as the legislators list.
Also worth noting that Senate committees largely do not have YouTube channels, but in cases where I could find those I added them, too.
> YouTube channel IDs for House and Senate committees, where applicable

- scripts/alternate_bulk_formats.py
In the alternate bulk format script, we were printing that we were converting the files to YAML when we are really converting them to CSV. Also, one of the messages that said this was missing.
> Fix a typo and add a missing progress message in formatting script

- README.md
It seems like the Travis-CI integration is no longer used, so this change updates the badge shown in the README to show the CircleCI badge instead.
> Update build status badge in README for CircleCI

- legislators-current.yaml
These two records display `?` where they should have `"` or `'`.
> Fixed family members with " or ' in the name

- legislators-district-offices.yaml
- scripts/office_validator.py
Add validator for office zip.
Fix type issues in `legislators-district-offices.yaml`.
* Fixes zip codes being parsed as integers instead of strings.
* Fixes dashes in phone numbers.
Fixes #799.
Both issues were introduced in #794 (fcabd4c9e152885a1d6f242e0a3c878ce3d4cbab).
> Fix type issues in `legislators-district-offices.yaml`

- legislators-social-media.yaml
- scripts/data/social_media_blacklist.csv
Add account for Rep. David G. Valadao.
Update accounts for Sen. Rand Paul and Sen. James M. Inhofe.
Add 'home' and 'intent' to Twitter blocklist.
----
Justification:
* [\@RepDavidValadao](https://twitter.com/RepDavidValadao) links to Valadao's House website, which links back.
* [\@SenRandPaul](https://twitter.com/SenRandPaul) identifies itself as an official government account and links to Paul's Senate website, which links back. [\@RandPaul](https://twitter.com/RandPaul), on the other hand, links to Paul's campaign website.
* [\@JimInhofe](https://twitter.com/JimInhofe) links to Inhofe's Senate website, which links back. [\@InhofePress](https://twitter.com/InhofePress) also links to it. His campaign account appears to be [\@inhofeforsenate](https://twitter.com/inhofeforsenate).
Not …
> Update Twitter accounts

- legislators-current.yaml
Per 1c13038c407069393bd578009cb025700e57da2c, our policy is to make the first name field of legislators a name that would be recognized by the general public as the legislator's first name, even if it is not the legislator's legal first name, especially to follow the legislator's preferred first name in the Bioguide or House/Senate websites (which show "Madison" in this case).
> Revise Rep. Cawthorn's first name to Madison

- legislators-current.yaml
Added an identifier for Jake Ellzey based on [his Open Secrets page](https://www.opensecrets.org/members-of-congress/jake-ellzey/summary?cid=N00042243&cycle=2022).
> Add Open Secrets identifier for Jake Ellzey

- legislators-district-offices.yaml
Tampa changed locations + phone, cleaned up some other unlisted fax numbers for the rest of the locations.
From: https://www.rubio.senate.gov/public/index.cfm/contact
> Updated Rubio district offices

- legislators-current.yaml
Reported by a GovTrack user. Looks like it was a data entry error by the GovTrack team in ee290b5d.
> Fix gender of Rep. Salazar

- legislators-current.yaml
It's being widely reported today that Sinema has registered as an Independent. Although she hasn't said explicitly about caucusing with Democrats, Politico reports that she intends to get committee assignments from Democrats, which almost certainly means caucusing with the Dems. She also almost certainly voted in the Dem caucus leadership election a few days ago (since there was no reporting that she didn't).
https://www.politico.com/news/2022/12/09/sinema-arizona-senate-independent-00073216
> Change Sinema's party to Independent but caucusing with Democrats

- README.md
- legislators-social-media.yaml
- scripts/alternate_bulk_formats.py
From @danielschuman's spreadsheet at https://docs.google.com/spreadsheets/d/1egupogzhZgPgcM1NcIxBC4iW2xgvs1qJPAG568YaCuY/edit#gid=1071805829. Only confirmed accounts are added.
The CSV file of legislators is updated to include the Mastodon handles in a new column, and numeric Twitter IDs are added for completeness.
> Add Mastodon handles

- legislators-current.yaml
He was re-sworn in... late last night? It's not clear exactly at what time, but ending the appointment term on Dec 21 and starting the special election term on Dec 22 seems right.
https://twitter.com/CraigCaplan/status/1605793306377584641
> Correct Sen. Padilla's special election term start date from Nov 9 to Dec 22

- scripts/bioguide_xml.py
There were no discrepancies in current legislators, although the Bioguide data may not be complete for new legislators yet.
parse_birthday_from_text comes from our existing bioguide.py script which parses the HTML website directly.
> Update some historical birthdays by reading the Bioguide bulk JSON download with a new script

- committee-membership-current.yaml
- committees-current.yaml
- committees-historical.yaml
Following the conversation on https://github.com/unitedstates/congress-legislators/issues/875. I'm updating manually the files to reflect the current committees on 118th Congress.
This commit updates the `committees-current.yaml` file and `committees-historical.yaml` file to reflect the committees no longer standing from the 117th Congress.
This update was made manually.
> feat: Update no longer standing committees from 117th Congress

- committees-current.yaml
I'm a maintainer of Open States & this has been causing some issues with our `update` workflows, other committee names that need new lines are like the fixed code style like [this subcommittee](https://github.com/NewAgeAirbender/congress-legislators/blob/901859c9e5a0927f38d3f2cd4cf2e8bbb701459d/committees-current.yaml#L1216)
> Remove extra space from subcommittee name

- committee-membership-current.yaml
- committees-current.yaml
I did a manual audit of #886 and indeed, it looks the committees missing members are no longer listed in applicable house/senate websites.
Wasn't sure if `committees-historical.yaml` should be manually updated in concert (I'm not _currently_ using it).
> #886 - Update/defunct or dup committees

- legislators-district-offices.yaml
Per https://gomez.house.gov/contact/officeinformation.htm, the phone number for the office has changed. There's no fax line listed.
> Update Jimmy Gomez LA phone

- legislators-district-offices.yaml
Per her site, the Portland office number has changed: https://www.collins.senate.gov/contact
> Update Portland office number for Collins

- legislators-current.yaml
Seems to be wrong? I see this 
https://www.opensecrets.org/members-of-congress/thomas-h-kean-jr/summary?cid=N00027502&cycle=2022
> Update Opensecrets ID for Kean

- README.md
- legislators-current.yaml
- scripts/pictorial_ids.py
- test/test_pictorial_ids.py
- test/validate.py
Adds ids mapping to GPO's Pictorial Member Guide
pictorialapi.gpo.gov
This PR includes ids for all members of 118th Congress. It may also work for historical files -- at least going back to 110 -- but I have not included that work here, as it requires manual fixes and I imagine most interest is in current membership.
Closes #942
> Add pictorial ids, script for 118th Congress

- legislators-current.yaml
Her last name is simply Luna. It was incorrectly combined with her middle name, with it repeated in the middle name field, originally, in 1b0c1c92.
Reported by a GovTrack user.
> Fix Rep. Luna's last name, not "Paulina Luna"

- executive.yaml
As in the past, former legislators who serve as president or vice president get a duplicate entry in executive.yaml but only with their executive branch roles, so Vance is duplicated from legislators-historical.yaml.
> Add new Trump/Vance roles and correct Vance's name info

- legislators-current.yaml
I'm trying to improve fax coverage; Ed Markey is for sure correct as I pulled it right off of his Senate site, the others I trust the judgement of the core team whether or not to merge. They are indeed fax numbers, but the source is from 2022.
> Add Fax Numbers

- legislators-current.yaml
- legislators-social-media.yaml
Removed from current legislators and social media files, added to historical legislators.
> Removing Sylvester Turner, who died, from current legislators

- legislators-district-offices.yaml
```
Good afternoon!
Your software has a wrong fax number for our office. The correct fax line number for Representative Carol Miller is (771) 200-5618.
Best,
Nicolas Gray
Director of Constituent Services, Rep. Carol D. Miller 2699 Park Avenue, Suite 220, Huntington, WV 25704
(304) 522-2201 – Office | 771-200-5618 – Fax
```
> Carol Miller Fax

- legislators-district-offices.yaml
**Addressing validation errors**
The test/validate script noted a variety of errors regarding outdated data for district offices. This pull request contains up-to-date data, including updated geocoding, for those offices. All tests should pass.
**Senate Term Fixes**
Fixed several service term dates for select TX, AR historical senators as I was doing some research with the data in historical-legislators.yaml and noted some inconsistencies. This follows issues noted in #385  and #386:
* Lloyd Bentsen: retired to become Treasury Secretary, term end 1993-01-20 (https://bioguide.congress.gov/search/bio/B000401)
* Bob Kreuger: appt and lost election, term end 1993-06-14 (https://bioguide.congress.gov/search/bio/K000333)
* Kay Bailey Hutchison: won special election and began term on 1993-06-14 …
> Fixing test/validation errors for district office data and fixing select errant senate term data

- legislators-current.yaml
Fixes #845. Verified that the CSPAN IDs for the five legislators were incorrect and replaced them with the correct ones.
> Fix incorrect CSPAN IDs
