unitedstates/congress-legislators

legislators-current.yaml

note that new senators aren't finished here and will have to be done by hand.

Thomas IDs added to new reps where available

---

legislators-social-media.yaml

YouTube username hasn't been updated yet.

update Senator Cotton's Twitter and Facebook

---

legislators-social-media.yaml

I couldn't find a youtube username, but I got their channel ids. Based on issues #239 and #240, which can be closed once this is merged.

Added Sen. Ernst and Tillis

---

legislators-social-media.yaml

Just an alternate identifier code for their youtube accounts. Noticed a few were missing and so I added them.

Added a few missing youtube_ids

---

legislators-social-media.yaml

All of these are linked from *.house.gov and *.senate.gov pages.
h/t @nickom

Add a few Twitter accounts

---

legislators-current.yaml

to match other legislators of the same religious affiliation (Episcopal -> Episcopalian)

normalize religion value for Robert Wittman

---

legislators-current.yaml

www. for menendez' website

---

legislators-current.yaml

`http://mike-rogers.house.gov` -> `http://mikerogers.house.gov`

Mike Rogers' website moved

---

committees-current.yaml
legislators-current.yaml

senate urls prefer the "www." and many hostnames will not redirect to canonical name w/ the www.
--timball

fixes issue #278

---

committees-current.yaml

some cmtes were missing urls . this fixes #281 .
--timball

update missing urls

---

legislators-social-media.yaml

All added accounts are linked from her official site: https://radewagen.house.gov/

Added Rep. Aumua Amata.

---

legislators-current.yaml

Joe Crowley has a nickname , it's Joe . 
--timball

Joe is his nickname

---

scripts/utils.py

Noticed this constant is outdated. Should this be updated?

Now 114th Congress

---

legislators-social-media.yaml
scripts/data/social_media_blacklist.csv

Scanned tonight, resolved using @dannguyen's new resolving script.

A few new Twitter accounts

---

legislators-social-media.yaml

KirstenGillibrand facebook and twitter

---

README.md

Some .yaml files were not highlighted which made reading the text a bit difficult. I highlighted them as in-text-code to make it easier reading README.md file.

highlighted all .yaml files

---

legislators-current.yaml

http://www.opensecrets.org/politicians/summary.php?cid=N00037031&cycle=2016

added OpenSecrets ID for Darin LaHood

---

.travis.yml
README.md

Python 3.5 is out

---

legislators-social-media.yaml

see https://twitter.com/whoismyvoice/status/743152625265180672

correct albio sires twitter info

---

legislators-current.yaml

add OpenSecrets ID for Warren Davidson

---

README.md

Adds an explanation of what our social media data represents to the README.

Clarifies intent of our social media data

---

legislators-current.yaml

Swearing-in in the Congressional Record:
https://www.congress.gov/congressional-record/2017/01/10/house-section/article/H245-7
Background:
http://www.usatoday.com/story/news/politics/onpolitics/2017/01/10/kurt-schrader-takes-oath-after-skipping-first-week-honeymoon/96409286/

Push back Rep. Kurt Schrader's term-start date for the 115th Congress.

---

executive.yaml

This is a draft PR for merging on Jan 20 at noon. The President-elect needs to get a GovTrack ID entered before this can be merged, but otherwise it should be good to go.

add Donald Trump, Mike Pence to executive.yaml

---

.travis.yml
scripts/archive/committee_membership_house.py
test/validate.py

Test code is as important as production code, and should also be checked for errors.

Run pyflakes on all scripts, and fix them

---

committee-membership-current.yaml
committees-current.yaml
scripts/bioguide.py
scripts/committee_membership.py
scripts/wikipedia_ids.py

Ran the committee_membership.py script, and some related fixes.

115th Congress committee assignments

---

legislators-current.yaml
scripts/archive/print_leadership_roles.py

Manual update of leadership roles...
```
print_leadership_roles.py
Cornyn, John
senate Minority Whip started 2013-01-03 and ended 2015-01-03
senate Majority Whip started 2015-01-03 and ended 2017-01-03
senate Majority Whip started 2017-01-03 with no end
Durbin, Richard
senate Minority Whip started 2005-01-04 and ended 2007-01-03
senate Majority Whip started 2007-01-04 and ended 2009-01-06
senate Majority Whip started 2009-01-06 and ended 2011-01-05
senate Majority Whip started 2011-01-05 and ended 2013-01-03
senate Majority Whip started 2013-01-03 and ended 2015-01-03
senate Minority Whip started 2015-01-03 and ended 2017-01-03
senate Minority Whip started 2017-01-03 with no end
McConnell, Mitch
senate Minority Leader started 2007-01-04 and ended 2009-01-06
senate Minority Leader started …
```

115 leadership roles

---

legislators-current.yaml
scripts/senate_contacts.py

There seemed to be many issues with contact forms, this hopefully will fix most of them, but I question the value of keeping this list updated here as opposed to pointing people to https://github.com/unitedstates/contact-congress
The script got most of them, but the senate XML will often point to a contact landing page instead of the form itself, so its not totally reliable and this is a manual review process.

update senate contact forms

---

congress_lookup.py
legislators-current.yaml

Minor updates to database and lookup code

Remove spaces from fax numbers, unique lookups, current term filter

---

legislators-current.yaml

pull fax numbers from 114th forward

---

congress_lookup.py
legislators-current.yaml

Add a few new fax numbers, fix some fail lookup conditions and add a filter method for possible future use.

fax additions; sorted output, filter method, keys existence test

---

legislators-social-media.yaml

updates based on @soooh's comment in #293.
This is probably OK to go after some light review, but social media in general still needs a lot of scrutiny.

social media updates

---

congress_lookup.py

Python version independence

---

legislators-current.yaml
legislators-social-media.yaml
scripts/data/social_media_blacklist.csv
scripts/utils.py

Ran senate contacts and facebook/ig sweeps.  
did not run resolveig or resolvefb... I spent a few minutes trying to get the APIs working and gave up... if anyone has instructions on how to get these APIs working it would be good to get documented.  
For the instagram accounts, I checked accounts not starting with Rep or Sen for obvious campaign accounts, only found one.  I did not check them if they sounded official.

facebook and instagram sweeps, senate contacts

---

README.md
legislators-social-media.yaml
scripts/alternate_bulk_formats.py
scripts/social_media.py

remove facebook ids

---

legislators-current.yaml
legislators-social-media.yaml

Source: http://clerk.house.gov/floorsummary/floor.aspx?day=20170301&today=20170301

Ryan Zinke resigned.

---

legislators-current.yaml

Gillibrand's fax number was actually Faso's, fixed that and added Gillibrand's correct fax

fix gillibrand and faso fax numbers

---

legislators-current.yaml

run linter to fix build

---

scripts/house_contacts.py
scripts/senate_contacts.py

To keep house_contacts.py and senate_contacts.py from undoing the changes in #474

Use curly apostrophes in contacts scripts

---

legislators-current.yaml

Source: http://clerk.house.gov/floorsummary/floor.aspx?day=20170711&today=20170711

Add Rep. Jimmy Gomez, D-CA

---

legislators-social-media.yaml

Links from official sites:
- https://anthonybrown.house.gov/
- https://www.brown.senate.gov/
- https://cardenas.house.gov/
- https://correa.house.gov/
- https://guthrie.house.gov/
- https://hanabusa.house.gov/
- https://clayhiggins.house.gov/
- https://maloney.house.gov/
- https://smucker.house.gov/
- https://www.stabenow.senate.gov/
- https://www.strange.senate.gov/
- https://taylor.house.gov/

add official facebook accounts

---

legislators-current.yaml

This has several updates to Senate web forms and URLs, from running `senate_contacts.py`. A few moving from http -> https, a few fixes to URLs, and one update to office address.

Update a few Senate contact forms and websites

---

README.md
scripts/alternate_bulk_formats.py
scripts/office_validator.py
scripts/update_gh_pages.sh
test/validate.py

Small fixes to district office scripts:
- validator option to suppress warnings (used by CI validate script to reduce noise)
- add header row to district office CSV
- minor fix for validator script to prevent erroring on unknown fields

District office fixes

---

legislators-district-offices.yaml

Verified changes from house.gov site.

Update offices for Rep. Gianforte

---

scripts/office_validator.py

This only reports an error if the member has been in office for at least 60 days. See https://github.com/unitedstates/congress-legislators/issues/523

Allow new members without district offices

---

legislators-current.yaml

Source: http://clerk.house.gov/floorsummary/floor.aspx?day=20171113

Add John Curtis

---

legislators-district-offices.yaml

see the footer of: https://donyoung.house.gov/

update don young's anchorage office

---

committee-membership-current.yaml
legislators-current.yaml
legislators-social-media.yaml
scripts/committee_membership.py
scripts/house_contacts.py

Various data updates from scripts

---

legislators-current.yaml

add MapLight IDs for John Curtis, Doug Jones, Tina Smith
add OpenSecrets ID for Doug Jones

add MapLight and OpenSecrets IDs for new legislators

---

legislators-district-offices.yaml

There are a lot of changes in here, but here's the list of sources (with the bioguide ids to make it a bit more digestible). Some of the changes were just stylistic (e.g. using "suite" instead of "ste." to make everything match.)
- A000055 : https://aderholt.house.gov/contact/offices
- A000367 : https://amash.house.gov/contact/offices
- A000374 : https://abraham.house.gov/contact/offices
- A000375 : https://arrington.house.gov/contact/offices
- B000574 : https://blumenauer.house.gov/contact/offices
- B000575 : https://www.blunt.senate.gov/public/index.cfm/office-locations
- B001236 : https://www.boozman.senate.gov/public/index.cfm/office-locations
- B001250 : https://robbishop.house.gov/
- B001251 : https://butterfield.house.gov/contact/offices
- B001260 : …

district office updates

---

legislators-current.yaml
legislators-district-offices.yaml

Offices sourced from https://www.jones.senate.gov/content/contact-senator
Mobile and Montgomery offices do not list phone contacts
Geocoded with `python geocode_offices.py`

Doug Jones DC and District offices

---

scripts/alternate_bulk_formats.py

Added senate_class field to be in CSV files

---

legislators-current.yaml

Just getting this ready. The bioguide and LIS IDs are not up yet.

Sen. Cindy Hyde-Smith (draft)

---

legislators-district-offices.yaml

A few updates to the district office info. Here are the sources:
notes:
- A000367: https://amash.house.gov/
- B000490: https://bishop.house.gov/
- B000575: https://www.blunt.senate.gov/public/
- B001230: https://www.baldwin.senate.gov/
- B001243: https://blackburn.house.gov/contact/
- B001261: https://www.barrasso.senate.gov/public/
- B001267: https://www.bennet.senate.gov/?p=contact
- B001275: https://bucshon.house.gov/
- B001285: https://juliabrownley.house.gov/
- B001291: https://babin.house.gov/contact/officeinformation.htm
- B001294: https://blum.house.gov/
- B001296: https://boyle.house.gov/
- B001303: https://bluntrochester.house.gov/
- C000141: https://www.cardin.senate.gov/
- C000880: https://www.crapo.senate.gov/contact/office-locations

updated district office info

---

legislators-current.yaml
misc/new-member-template.yaml

A bioguide ID isn't yet posted.

added Rep. Lesko

---

legislators-current.yaml
legislators-district-offices.yaml

Hyde-Smith: https://www.hydesmith.senate.gov/content/offices
Lamb: https://lamb.house.gov/contact/offices
Lesko: https://lesko.house.gov/contact/offices

Update data for Hyde-Smith, Lamb, and Lesko

---

legislators-district-offices.yaml

G000581 - https://gonzalez.house.gov/contact/offices/falfurrias-office
K000392 - https://kustoff.house.gov/contact/offices/jackson-office
M001200 - https://mceachin.house.gov/contact/offices/hampton-roads-office
Y000065 - https://yoho.house.gov/contact/offices/ocala-district-office

Add new district offices for Gonzalez, McEachin, Kustoff, and Yoho

---

legislators-district-offices.yaml

Addresses:
G000582: https://gonzalez-colon.house.gov/contact/offices
R000580: https://roskam.house.gov/contact/offices
T000460: https://mikethompson.house.gov/contact/offices
Phones/Faxes:
A000055 - https://aderholt.house.gov/contact/offices
B001257 - https://bilirakis.house.gov/contact/offices
K000375 - https://keating.house.gov/contact/offices
M000087 - https://maloney.house.gov/contact/offices
M001200 - https://mceachin.house.gov/contact/offices
S001200 - https://soto.house.gov/contact/offices
W000816 - https://williams.house.gov/contact/offices

Various district offices updates

---

legislators-current.yaml

Per data here: https://voteview.com/static/data/out/members/S115_members.json

ICPSR ID fix and additions

---

legislators-current.yaml

If Kyl is sworn in today, here is that. I assumed he'd be using McCain's office so I copied forward that address. I also assumed Flake is now and would still be the senior senator.

Jon Kyl might be sworn in today

---

legislators-current.yaml

Just waiting for his bioguide ID to be posted. It'll probably be http://bioguide.congress.gov/scripts/biodisplay.pl?index=B001306 so I filled it in here, but we should wait to merge until we have it for real, assuming it comes soon.

add Troy Balderson, fixes #598

---

legislators-district-offices.yaml

https://cloud.house.gov/contact/offices
https://balderson.house.gov/contact/offices

Add offices for Balderson and Cloud

---

scripts/alternate_bulk_formats.py

Add additional name fields to CSV.
Addresses #605.

Add name fields to CSV export

---

legislators-district-offices.yaml

Updates to various senate offices. Sources:
B001135 : https://www.burr.senate.gov/#wilmington
C001098 : https://www.cruz.senate.gov/?p=general&id=23
F000463 : https://www.fischer.senate.gov/public/index.cfm/office-information
H001041 : https://www.heller.senate.gov/public/
H001061 : https://www.hoeven.senate.gov/contact/office-locations
H001079 : https://www.hydesmith.senate.gov/content/offices
I000024 : https://www.inhofe.senate.gov/
K000393 : https://www.kennedy.senate.gov/public/
R000584 : https://www.risch.senate.gov/public/
R000595 : https://www.rubio.senate.gov/public/index.cfm/miami-office
S001198 : https://www.sullivan.senate.gov/contact/locations
T000250 : https://www.thune.senate.gov/public/index.cfm/regional-updates
T000476 : …

updated office locations

---

legislators-current.yaml
legislators-district-offices.yaml

Offices found from https://www.kyl.senate.gov.

Update website and add district offices for Kyl

---

legislators-current.yaml

Rep. Scanlon was also sworn in yesterday and [voted](http://clerk.house.gov/evs/2018/roll417.xml).

Nov 2018 Special Election Results - Scanlon

---

legislators-current.yaml

https://twitter.com/CraigCaplan/status/1067394564007387138

Rep. Wild (PA-15) will be sworn in today

---

legislators-current.yaml

She is expected to be sworn in today:
https://twitter.com/CraigCaplan/status/1068164538879696896
I couldn't find her birthday besides Oct. 1959 on Wikipedia (https://en.wikipedia.org/wiki/Brenda_Jones_(politician)) so I put in Oct 1 provisionally.

Rep. Jones (MI-13) elected in special election

---

legislators-current.yaml
legislators-district-offices.yaml

* Add URLs for newly sworn in members.
* Ran house_contacts.py to pick up official_full names as well as changes to addresses.
* Added district office information for new members, verifying through their official websites.

Update member and district office information

---

legislators-current.yaml

Ran `house_contacts.py` and `bioguide.py`. Added Jared Golden (ME-2), and added URLs for all legislators missing URLs except for Rick Scott.
Closes #634 and closes #632.

Add Jared Golden and update member data

---

legislators-social-media.yaml

These came from a crawl of *.house.gov pages of each, and were then hand verified for a "checkmark" on twitter, along with some representation of the official account. They are on the bottom...

Official accounts for 14 Freshmen

---

legislators-social-media.yaml

This adds additional accounts not contained in #633.

Add Twitter accounts for some House members

---

legislators-current.yaml

I paid $1 at intelius.com to get the guy's birthday.

add birthday for Rep. Cisneros, according to intelius.com

---

legislators-social-media.yaml

Added ~50 Twitter accounts for House freshmen.

added more House freshmen twitter accounts

---

legislators-current.yaml

https://twitter.com/HouseDailyPress/status/1082714812877103105

Update 116h Congress term start date for Walter Jones.

---

legislators-current.yaml

https://twitter.com/CraigCaplan/status/1082747741623726082

Update start date for Sen. Rick Scott

---

congress_lookup.py
legislators-current.yaml
scripts/contact_forms.py

This PR adds leadership from https://www.house.gov/leadership and http://www.senate.gov/senators/leadership.htm. Fixes #654.
I changed the way titles were done in the past: Titles now all have "House" or "Senate" in them so that the title can be fully understood without knowing the context of the relevant chamber. So, where we had Minority Leader before, this PR makes it House/Senate Minority Leader, which I think is clearer and more accurate since this data is typically displayed in applications that show information for Congress as a whole rather than just one chamber. I went back to historical leadership data and updated those titles to match as well.
I assumed all of the roles started on Jan 3 --- not sure if that's true.
I also made some changes to the official titles e.g. replacing …

add leadership for the 116th Congress

---

legislators-social-media.yaml

Easier for maintenance to keep all of a member's social media accounts under one record.

Merge social media records for Bill Cassidy (C001075)

---

legislators-district-offices.yaml

Ref: https://underwood.house.gov/contact/offices

update lauren underwood's office

---

legislators-current.yaml

@amyewest called his office and asked.

Add Rep. Murphy's birthday

---

legislators-current.yaml

As @dwillis posted on Twitter, Rep. Van Drew changed parties in a FEC filing on Dec 19: https://docquery.fec.gov/cgi-bin/forms/H8NJ02166/1367072/

Van Drew changed parties

---

legislators-current.yaml
scripts/utils.py
test/validate.py

Fix term date errors that prevented assigning Congress numbers to terms

---

legislators-current.yaml

Doesn't have govtrack id (cc @JoshData)

Adds Chris Jacobs

---

legislators-current.yaml
scripts/house_contacts.py

Closing PR #734 and opening this PR that both removes the addition of a semi-colon after full office building for consistent address formatting and commits the updated legislators-current.yaml file.

Create consistent address format for contact data

---

legislators-social-media.yaml

Added Mark Kelly social accounts

---

legislators-current.yaml

https://twitter.com/RepPaulMitchell/status/1338599898141356034

Rep. Mitchell leaves Republican Party

---

legislators-current.yaml
legislators-social-media.yaml
scripts/senate_contacts.py

If bioguide IDs become available before the end of the day I'll add them and remove the commit that removes the bioguide validation.

Senators Padilla filling Harris's recent vacancy, Warnock replacing Loeffler whose term now ends, and Ossoff

---

legislators-current.yaml
legislators-district-offices.yaml
legislators-social-media.yaml

https://www.dallasnews.com/news/politics/2021/02/08/rep-ron-wright-dies-after-battle-with-covid-19/

Rep. Wright died yesterday from covid

---

.gitignore
legislators-district-offices.yaml

Added Kweisi Mfume Dist. Offices per https://mfume.house.gov/contact/offices
NOT geocoded

+Kweisi Mfume district offices

---

legislators-current.yaml
legislators-district-offices.yaml
legislators-social-media.yaml

It was effective immediately a short time ago. https://twitter.com/CraigCaplan/status/1371888803439345672

Rep. Haaland resigned to be Secretary of the Interior

---

legislators-social-media.yaml

Correct handle: https://twitter.com/RepMondaire

Fix Rep. Jones Twitter Handle

---

legislators-current.yaml

No bioguide ID is up yet so I'm starting this PR as a draft.

Rep. Julia Letlow sworn in

---

legislators-current.yaml

Added missing parameter official_full to julia letlow in legislators legislators-current.yml

Added missing parameter official_full 

---

README.md
congress_lookup.py
scripts/contact_forms.py
scripts/run_script_to_branch
scripts/update_gh_pages.sh

it looks like the publish step is still failing, updated master->main in that script as well as a few others

a few other fixes where master should have been changed to main

---

README.md
committee-membership-current.yaml
committees-current.yaml
scripts/committee_membership.py

Probably some review needed here, especially around subcommittees and joint committee handling.  Refs #276
```
committee_membership_sanity_check.py
HLIG    : 22
HLIG01 : 10
HLIG02 : 10
HLIG03 : 10
HLIG04 : 10
HSAG    : 46
HSAP    : 52
HSAS    : 62
HSBA    : 60
HSBU    : 33
HSED    : 39
HSFA    : 47
HSGO    : 38
HSGO06 : 9
HSGO24 : 14
HSGO25 : 8
HSGO27 : 10
HSGO28 : 6
HSGO29 : 8
HSHA    : 9
HSHM    : 30
HSIF    : 55
HSIF02 : 17
HSIF03 : 31
HSIF14 : 31
HSIF16 : 29
HSIF17 : 22
HSIF18 : 22
HSII    : 42
HSJU    : 41
HSJU01 : 13
HSJU03 : 26
HSJU05 : 13
HSJU08 : 17
HSJU10 : 8
HSPW    : 61
HSPW02 : 30
HSPW05 : 37
HSPW07 : 14
HSPW12 : 48
HSPW13 : 13
HSPW14 : 32
HSRU    : 13
HSSM    : 18
HSSM23 : 3
HSSM24 : 4
HSSM25 : 6
HSSM26 : 6
HSSM27 : 5
HSSO    : 9
HSSY    : 31
HSVR    : 21
HSVR03 : 12
HSVR08 …
```

Update House committee membership using House XML data

---

legislators-current.yaml

added Sheila Cherfilus-McCormick

---

executive.yaml

Merge two Joe Biden records in executive.yaml

---

executive.yaml

Birthdates: Hoover, Eisenhower
Gender: Ford, Rockefeller

Added missing information

---

legislators-social-media.yaml
scripts/requirements.txt
test/validate.py

* Add some basic checks.
* If a TWITTER_API_BEARER_TOKEN environment variable is set, query the Twitter API to check that Twitter usernames and IDs match, and if usernames are in canonical case.
* Fix Rep. Coons's twitter_id to match the twitter handle. The existing ID corresponds to the Twitter handle SenCoonsOffice which also appears to be a correct account, but his website links to the ChrisCoons account.
* Update various Twitter handles to TitleCase if the account itself uses TitleCase

Add new validation tests for the social media file

---

legislators-current.yaml

Reps. Ellzey, Carey, and Cherfilus-McCormick.
Resolves validator warnings.

Add missing legislator URLs

---

legislators-district-offices.yaml

See https://github.com/openstates/issues/issues/717; two of the offices are out of date.

Update Marsha Blackburn's district offices

---

legislators-current.yaml

Source: https://finstad.house.gov/

Add Brad Finstad DC Phone

---

legislators-current.yaml
test/validate.py

Sworn in on September 13, 2022

Add Rep. Mary Peltola

---

legislators-current.yaml

fix: Correct contact form URL for Senator John Hoeven and Tina Smith

---

legislators-current.yaml

Planned for tomorrow evening, per https://twitter.com/ChadPergram/status/1591854464398680065.
Still missing a bioguide ID and birthdate.
---
I may be off-line for a lot of the next month so if there are other updates, I may not be able to get them started. I do plan to work on the 118th Congress updates with the help of the GovTrack team in mid/late December.

Rep. Rudy Yakym sworn in after special election

---

legislators-current.yaml

Reverts unitedstates/congress-legislators#852

Revert "Rep. Rudy Yakym sworn in after special election"

---

legislators-current.yaml
test/validate.py

Fix missing party_affiliations start/end dates in #856 

---

legislators-current.yaml

Added URLs for new House members.

Added urls for 118th House

---

legislators-current.yaml

Mentioned in #867. For [Laurel Lee](https://bioguide.congress.gov/search/bio/L000597), for whom the biographical directory has no month or day listed, DOB was confirmed by calling her office.

Added several missing birthdays

---

legislators-current.yaml
legislators-district-offices.yaml
legislators-social-media.yaml

https://www.congress.gov/congressional-record/volume-168/issue-189/senate-section/article/S7003-3

Sen. Sasse resigned on Jan. 8

---

legislators-social-media.yaml

Still missing a handful of members but will do another sweep in a week or so.

Added twitter accounts for most 118th members

---

legislators-current.yaml

Some of the addresses were updated when I ran the 'house_contacts.py' script. 
First time contributor, feedback welcome!

Updated addresses

---

legislators-current.yaml

Added Sen. Ricketts, fixed Gluesenkamp Perez's first name

---

committee-membership-current.yaml
committees-current.yaml
legislators-current.yaml
scripts/committee_membership.py

Committe membership update, Senate address updates

---

legislators-current.yaml

This PR adds leadership from https://www.house.gov/leadership and http://www.senate.gov/senators/leadership.htm.
Please revise as needed.
Closes: https://github.com/unitedstates/congress-legislators/issues/877
Modeled After: https://github.com/unitedstates/congress-legislators/pull/660
Name | Official Title | Title in this Pull Request
-- | -- | --
Patty Murray | President Pro Tempore | President Pro Tempore of the Senate
Mitch McConnell | Republican Leader | Senate Majority Leader
John Barrasso | Republican Conference Chairman | Senate Republican Conference Chair
Shelley Moore Capito | Vice Chairman of the Senate Republican Conference | Senate Republican Conference Vice Chair
Joni Ernst | Republican Policy Committee Chairman | Senate Republican Policy Committee Chair
Chuck Schumer | …

118th congress leadership

---

committees-current.yaml

Remove extra space from cyber subcommittee

---

legislators-current.yaml

This PR corrects what might have been a prior typo made when updating current leadership roles

Correct typo in McConnell's current leadership

---

committees-current.yaml

Remove stale Nunes reference.
Tangentially relates to #886

Update HLIG jurisdiction description

---

legislators-current.yaml

Following adoption of H. Res. 757 vacating the office.
I think it will be https://clerk.house.gov/evs/2023/roll519.xml when it is posted.

End Rep. McCarthy's leadership_role for Speaker of the House

---

legislators-district-offices.yaml

Updated office locations for Salud Carbajal, per his site: https://carbajal.house.gov/contact/officeinformation.htm

Updated office locations for Salud Carbajal

---

legislators-district-offices.yaml

Same as Feinstein, though no faxes and office hours are noted so they've been removed.
https://www.butler.senate.gov

Local offices for laphonza butler

---

legislators-district-offices.yaml

The only local office listed is this one in Farmington Hills now
https://stevens.house.gov/contact/offices/farmington-hills-district-office-0

Update local office for Haley Stevens

---

legislators-district-offices.yaml

Update Peter Welch's Burlington office

---

.gitignore
legislators-current.yaml

Except for Laphonza Butler, appointed CA Senator, who has no OpenSecrets id because she
has never raised money.
Closes #913

Added all missing opensecrets ids

---

legislators-current.yaml
legislators-district-offices.yaml
legislators-social-media.yaml

Won special election in NY-26; sworn in on May 6.

Added Timothy Kennedy

---

legislators-current.yaml

Sworn in on July 8, replacing Ken Buck.

added Greg Lopez

---

executive.yaml

Added some missing identifiers for recent executive listings.

Add missing identifiers to Barack Obama, Donald Trump and Mike Pence

---

committee-membership-current.yaml

Update committee membership to capture new Senator George S. Helmy's committee assignments.

Update committee membership 

---

legislators-district-offices.yaml

Hi again, 5 Calls uses legislator data in this repo and has an interest in keeping district office info updated as alternative phone numbers for constituents to call. I've tried manually keeping this info up-to-date when users tell us it's outdated but it's a pain and doesn't scale. The mechanical turk tool is nice but I wanted something with a faster turnaround time. I experimented with automating this via LLMs and it turned out surprisingly well.
This represents 783 new offices, 406 old offices removed, and added 162 new legislators which had no offices previously.
This data is generated from my new tool, [office-finder](https://github.com/nickoneill/office-finder), which extracts office data from website text for all house and senate websites in about 10 minutes for about $0.20 in …

updated offices for... almost everyone

---

legislators-current.yaml

Birthday is from Wikipedia since Bioguide only lists the year.

Added Rep. McIver

---

legislators-current.yaml
scripts/senate_contacts.py

I updated senate_contacts.py to better handle some duplicate contact form URLs that are in the cfm xml and then ran it against the current list.

Ran senate_contacts.py, small contact form processing update

---

legislators-current.yaml

Ran the existing house_contacts.py processor for new addresses and DC phone numbers.

Ran house_contacts.py for 2025

---

legislators-current.yaml

Added missing House urls for new members

---

legislators-current.yaml

Fax numbers for:
- Cliff Bentz (OR)
- Val Hoyle (OR)
- Chris Smith (NJ)

Fax Numbers

---

legislators-current.yaml

Source: https://www.schiff.senate.gov/services/help-with-a-federal-agency/

Add Senate Fax for Adam Schiff

---

committee-membership-current.yaml
committees-current.yaml
legislators-current.yaml

Adding the new reps from Florida to the data, per this issue https://github.com/unitedstates/congress-legislators/issues/1000

Adding Patronis and Fine

---

legislators-current.yaml

N.C. Legislator Faxes

---

legislators-current.yaml

Fixing the hyphens on some fax numbers from – to -

Fix fax number format
